In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11)    #Similar to range of Python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)    #Similar to range of Python

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(11)    #Similar to range of Python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))    #Pass tuple of dimensions

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((4,5))    #Pass tuple of dimensions

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)  #Returns a vector with ten evenly spaced points from start to stop

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
#linspace takes 3rd arg as no of oints aI want, range takes only step size

In [19]:
np.eye(4)  #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.89176307, 0.08366229, 0.44762752, 0.62029255, 0.5134157 ])

In [21]:
np.random.rand(5,5)  #Gives array of size 5x5

array([[0.69579161, 0.37254205, 0.10829513, 0.4108525 , 0.06783396],
       [0.63297231, 0.61905101, 0.76563474, 0.80168348, 0.6118076 ],
       [0.96507409, 0.90677619, 0.21181443, 0.02474701, 0.69060955],
       [0.55168772, 0.98520702, 0.5562464 , 0.91135942, 0.72965394],
       [0.61366715, 0.16334714, 0.04564317, 0.77064913, 0.70585846]])

In [22]:
np.random.randn(2)   #random noos centered around 0    Helpful for Gaussian Values

array([0.38559301, 0.93002209])

In [23]:
np.random.randn(4,4)

array([[-0.73117789, -1.95887677,  0.84061234,  0.10032956],
       [ 0.09362828,  0.36579947, -0.50315125,  0.01123289],
       [-0.55505205,  0.1010181 ,  0.98159116,  0.83765861],
       [ 1.13666828, -0.42582257,  1.0129474 , -0.65480984]])

In [24]:
np.random.randint(1,100)  #Return random integers from `low` (inclusive) to `high` (exclusiv

80

In [25]:
np.random.randint(1,100,10)

array([31, 53, 41,  4,  9, 34,  2,  9, 26, 17])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([42, 47, 18, 37, 46, 33, 21, 22,  3, 47])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([42, 47, 18, 37, 46, 33, 21, 22,  3, 47])

In [32]:
ranarr.max()

47

In [33]:
max(ranarr)

47

In [35]:
ranarr.argmax()    #First Index location of the largest no

1

In [36]:
ranarr.argmin()

8

In [37]:
ranarr.min()

3

In [39]:
arr.shape    

(25,)

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [47]:
from numpy.random import *

In [48]:
randint(2,10)

7

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [57]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[0:5] = 100

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [61]:
arr = np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
slice_of_array = arr[:6]

In [64]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_array[:]=99

In [66]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
#Org array also changes inorder to reduce memory consumption for bigger datasets

In [69]:
arr_copy = arr.copy()

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
arr_copy[:]=100

In [73]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
# copy method akes a copy

In [76]:
########### 2D ##########

In [77]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d[0][0]

5

In [81]:
arr_2d[0]

array([ 5, 10, 15])

In [82]:
arr_2d[1][1]

25

In [84]:
arr_2d[2][1]

40

In [80]:
#OR

In [85]:
arr_2d[2,1]  #Commma replaces sq brackets... recommended

40

In [86]:
arr_2d[2,2]

45

In [87]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
''' For Upper Right corner
'''

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [90]:
'''For Lower left Corner
'''

arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [91]:
# to fetch 25 and 30

arr_2d[1][1:]

array([25, 30])

In [92]:
#To fetch 35,40,45

arr_2d[2]

array([35, 40, 45])

In [93]:
## COnditional Selection###

In [94]:
arr = np.arange(0,11)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
bool_arr = arr>5

In [98]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [99]:
arr[bool_arr]   #Grab only those instances were bool array was true

array([ 6,  7,  8,  9, 10])

In [100]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])

In [101]:
arr_2d = np.arange(50).reshape(5,10)

In [102]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [103]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [109]:
arr_2d[arr_2d>4].shape

(45,)

In [111]:
arr_2d[arr_2d>4].reshape(5,9)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [112]:
### NUmpy Opern ###

In [113]:
arr = np.arange(11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [119]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [120]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [121]:
#Does not change the org array

In [122]:
1/0

ZeroDivisionError: division by zero

In [123]:
arr/arr    #Just gives a warning, but code runs

C:\Users\abhra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [125]:
1/arr   #signifies inf for infinty

C:\Users\abhra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [126]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [127]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [128]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [129]:
np.max(arr)

10

In [131]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [132]:
np.log(arr)

C:\Users\abhra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [157]:
#Make an array of 10*10 size where each element is a random integer between 0,100


arr_mix = randint(0,100,size=(10,10))

In [158]:
arr_mix


array([[24, 72, 64,  2, 57, 98, 61, 24, 68,  6],
       [37, 77, 30, 34, 26, 21,  0, 40, 60, 77],
       [79, 84, 99, 65, 86, 97, 70, 99, 28, 45],
       [85, 20, 85, 98, 36, 98, 34, 46, 55, 53],
       [18,  5, 64, 67,  4, 51, 78, 59, 10, 63],
       [68, 68, 77, 67, 11, 62, 65, 41, 20, 99],
       [58, 99, 14, 51, 29, 19, 50, 98, 91, 97],
       [88, 27, 25, 52, 21, 87, 90, 23, 76, 41],
       [ 6, 65, 20, 25, 83,  8,  4, 88, 63, 56],
       [73, 10, 31, 93, 20, 14,  6, 62, 21, 98]])